name: Build GUI exe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: gui

    - uses: actions/upload-artifact@v2
      with:
        name: config-tool
        path: gui/dist/windows/YuanConCFWConfig.exe
